apiVersion: v1
kind: Namespace
metadata:
  name: backend-app
  labels:
    name: backend-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend-app
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: gcr.io/gitlab-441915/backend-app:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: gcr-json-key

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
