apiVersion: v1
kind: Namespace
metadata:
  name: backend-app
  labels:
    name: backend-app #namespace

---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnY3IuaW8iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJ3aW5jcmVkIiwKCSJjcmVkSGVscGVycyI6IHsKCQkiYXNpYS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiZXUuZ2NyLmlvIjogImdjbG91ZCIsCgkJImdjci5pbyI6ICJnY2xvdWQiLAoJCSJtYXJrZXRwbGFjZS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkic3RhZ2luZy1rOHMuZ2NyLmlvIjogImdjbG91ZCIsCgkJInVzLmdjci5pbyI6ICJnY2xvdWQiCgl9LAoJImN1cnJlbnRDb250ZXh0IjogImRlZmF1bHQiLAoJImNsaVBsdWdpbnNFeHRyYURpcnMiOiBbCgkJIkM6XFxQcm9ncmFtIEZpbGVzXFxSYW5jaGVyIERlc2t0b3BcXHJlc291cmNlc1xccmVzb3VyY2VzXFx3aW4zMlxcZG9ja2VyLWNsaS1wbHVnaW5zIgoJXSwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfQoJfQp9
kind: Secret
metadata:
  name: gcr-json-key
  namespace: backend-app
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend-app
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: gcr.io/gitlab-441915/backend-app:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: gcr-json-key

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
